# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Mapbiomasfogo
                                 A QGIS plugin
 Este plugin permite acesso aos produtos de fogo do Mapbiomas diretamente no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-05
        copyright            : (C) 2025 by IPAM Amazonia
        email                : contato@mapbiomas.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Mapbiomasfogo class from file Mapbiomasfogo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    try:
        print("[MapBiomas Fogo] Iniciando carregamento do plugin...")
        from .MapBiomas_fogo import Mapbiomasfogo
        print("[MapBiomas Fogo] Plugin carregado com sucesso")
        return Mapbiomasfogo(iface)
    except Exception as e:
        import traceback
        print(f"[MapBiomas Fogo] ERRO ao carregar plugin: {e}")
        traceback.print_exc()
        raise
